### ISSUE TITLE
Remove center align from choicelist.py

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#2877]
openatv 7.2

**Describe the bug / Actual behaviour:**
choicelists have offsets defined in skin.xml parameters lists. But RT_VALIGN_CENTER has been added to these element and other similar list elements

		<parameter name="ChoicelistDash" value="0,3,1002,78"/>
	    <parameter name="ChoicelistName" value="68,20,919,78"/>
        <parameter name="ChoicelistIcon" value="15,20,38,38"/>

**Expected behaviour:**
Visit a screen that has a choicelist component and the offset for the button and text should match what the skinner has set in the skin parameters. 

**Actual behaviour** 
The element is center aligned but then offset again using the parameters. Meaning they are over offset. 

**Has this issue started to happen just recently?**
The commit by IanSav on Mar 28 2022 was one of the causes of this issue

No element that has a skin parameter offset should have RT_VALIGN_CENTER alignment added. 

Channelselect menu is an easy place to find this issue.

**Comment by kiddac** [comment]
@AbuBaniaz thinks this is corrected in version 7.3
I am testing version 7.2

I have just amend the choicelist.py file locally and removed RT_VALIGN_CENTER from all the eListboxPythonMultiContent elements and everything then shows correctly.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/pull/2878/commits/c3d47cd5d24d433c0a295320551695dbdd5b2ce9

**Comment by kiddac** [comment]
Thanks for your reply. 

The offset was probably included both horizontally and vertically to accommodate and align to the skinners button/icon size in choicelists 

[button][list value]

So it needs the left offset, so it doesn't overlap the button. And the top offset was probably included at the same time. 

Automatically centering these list values is better in the long run. I agree. (No more screenshots in photoshop and nudging a few pixels to get the desired result)
But to prevent confusion maybe the ChoiceListName offsets get removed, and the left offset is calculated from the ChoiceListIcon values. (plus a little extra padding)

If all image teams could agree to do that, that is a much better solution. 

Thanks for the work around. I will put it in my skins.

**Comment by AbuBaniaz** [comment]
Kiddac's skins are mainly for ATV and some users on ViX.

Skins from other images will not work on ATV, and vice versa. (Skins with python files/plugin included are obviously different).

**Comment by AbuBaniaz** [comment]
The Multiboot Manager screen is still broken. In simple, concise terms, what needs to be changed to adapt this to new ATV code. 

![atv_multiboot](https://github.com/openatv/enigma2/assets/6644489/27f6e337-18b9-4756-b910-60470ff916da)



https://github.com/kiddac/Slyk_Q_1080/blob/master/Slyk_Q_1080/usr/share/enigma2/slyk-q-1080/q-openatv.xml#L818:L825

```
	<screen name="MultiBootManager" position="0,0" size="1920,1080" flags="wfNoBorder" backgroundColor="transparent">
		<panel name="template1"/>
		<ePixmap pixmap="q-backgrounds/setup-bg.png" alphatest="blend" position="540,384" size="1002,623" zPosition="1"/>
		<widget name="slotlist" textOffset="15,0" position="540,385" size="1002,624" font="Regular;33" secondfont="Regular;33" foregroundColor="white" backgroundColor="mid" backgroundColorSelected="select-darkblue-bg" selectionPixmap="q-selectbars/q-menu-2.png" itemHeight="78" enableWrapAround="1" scrollbarMode="showNever" transparent="1" zPosition="2"/>
		<panel name="New-Buttons-T1"/>
		<widget source="description" render="Label" position="540,140" size="1002,195" font="Regular;33" foregroundColor="white" backgroundColor="topmid" transparent="1"/>
		<ePixmap pixmap="buttons/key_help.png" position="1845,1030" size="38,38" alphatest="blend"/>
	</screen>
```

**Comment by IanSav** [comment]
This looks a lot like the issues we were specifically targeting to fix in the openATV code.  If the screen had no vertical text offsets and allowed the default centering then the code would simply center the text for you.  By over-specifying details of the screen you are restricting how the code can help you.

From the came of this file you appear to have openATV specific skin/screen code just for openATV.  I would suggest that you optimise that code for the new openATV enhancements and then we can remove the top/center hack.
